apiVersion: v1
kind: Service
metadata:
  labels:
    name: enterprise-contract-controller
  name: metrics-service
  namespace: enterprise-contract
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    name: enterprise-contract-controller
