apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: enterprisecontract
spec:
  latestResourceSchemas:
    - md5-7c178a69bea3d98cde5f39a383ffd1a8.enterprisecontractpolicies.appstudio.redhat.com
